### ISSUE TITLE
server.lua:8: 'then' expected near '?'

### ISSUE THREAD

**Issue by ZimeZy** [MrDaGree/ELS-FiveM#100]
### Bug Description
Hello, I have just installed ELS on the FiveM Server which I am hosting and came across this issue which i can't find a fix to (I'm sorta new) 
@ELS-FiveM/server/server.lua:8: 'then' expected near '?'

I have added ELS Vehicles in and changed the VCF File. But I have no clue how to fix this

**Comment by MrDaGree** [comment]
Duplicate of #99
