### ISSUE TITLE
Els primary lights won't work when dro1, only leds but then the rotating lights don't work. Sirensettings is on 5.

### ISSUE THREAD

**Issue by TehSiXxYy** [MrDaGree/ELS-FiveM#106]
Els primary lights won't work when dro1, only when i write leds it blinks but then the rotating lights don't rotate. Sirensettings is on 5.
![Screenshot_1](https://user-images.githubusercontent.com/85306356/120680336-79a81b80-c49a-11eb-82f5-45a1aa053f0b.png)

I'm using version 1.1.2 2021.1

**Comment by TehSiXxYy** [comment]
My code didn't show up :'(

**Comment by MrDaGree** [comment]
DRO1 Patterns never got implemented nor will they.
