### ISSUE TITLE
Not working with WMServerSirens?

### ISSUE THREAD

**Issue by Anonymouse0104** [MrDaGree/ELS-FiveM#112]
### Bug Description
I would like to use  WMServerSirens with this ELS. The ELS itself works great, but if I add RequestScriptAudioBank(“DLC_WMSIRENS\SIRENPACK_ONE”, false) to the client.lua it gives me no error but also no sound.

Any idea how I can fix this so that the ELS uses the sirens from WMServerSirens?
https://github.com/Walsheyy/WMServerSirens

Would be great!

### Reproductive Steps
No clue

### Expected Behavior
Server sirens should change the sound of the sirens, but I get no error and no sound also

### ELS Information
* Version #: v1.1.2
* Server Version #: SERVER v1.0.0.4838 win32

**Comment by SkyHighModifications** [comment]
have you got this sorted?

**Comment by MrDaGree** [comment]
ELS has not been, nor planned to be, updated by myself. Others are more than welcome to submit PR's but from this time on I will only be working on [ELC FiveM](https://forum.cfx.re/t/paid-emergency-lighting-control-els-replacement-no-repair-glitch-28-lights/1047254/)
