### ISSUE TITLE
Load vcf .xml on linux

### ISSUE THREAD

**Issue by baalexan** [MrDaGree/ELS-FiveM#13]
Hi,

Linux is CaseSensitive for file then when ELS try to load .xml with vcf.lua file, he can't find police2.xml etc because in the vcf.lua he is write : POLICE2.xml

-----------
I don't know if u are french but ... 
Salut,

Linux est sensible à la case, du coup quand ELS fait appelle à vcf.lua, il essaye de charger POLICE2.xml alors qu'il s'appelle police2.xml.

**Comment by MrDaGree** [comment]
This is a problem with fivem server. 

Salut c'est un problème qui est avec le serveur fivem
