### ISSUE TITLE
vcf_files

### ISSUE THREAD

**Issue by Nxssie** [MrDaGree/ELS-FiveM#16]
Failed to execute thread: server/server.lua:678: attempt to get length of a nil value (global 'vcf_files')

```
AddEventHandler('onResourceStart', function(name)
	if name:lower() == GetCurrentResourceName():lower() then
		patternInfoTable.primarys = {}
		patternInfoTable.secondarys = {}
		patternInfoTable.advisors = {}
	    for i=1,#vcf_files do
	    	local data = LoadResourceFile(GetCurrentResourceName(), "vcf/" .. vcf_files[i])

		    if data then
		        parseObjSet(data, vcf_files[i])
		    end
	    end
```

**Comment by MrDaGree** [comment]
Well what does the VCF table look like?

**Comment by Nxssie** [comment]
i've tried to solve it but i couldn't so, i downgrade it to 1.3fix again

**Comment by MrDaGree** [comment]
Im assuming you updated and didnt add in the vcf and replaced the config. Replace everything but vcf's and then redo the vcf.lua.
