### ISSUE TITLE
Stage 1 rear brake lights still flashing

### ISSUE THREAD

**Issue by Gibster99** [MrDaGree/ELS-FiveM#17]
This is for V1.1.3a
Just migrated my server from Windows to Linux, after doing the necessary modifications to the config file so Linux can reference xml file names, I am having an issue when the car is at stage 1 of lights and stage 3. 

At stage 1 the rear brake lights that would be flashing but no other lights, at stage 2 everything is functioning normally, however at stage 3 all lights are flashing except for the rear brake lights. 

Detailed in these gifs:

Stage 1: https://puu.sh/Bfzrj/6149962fe7.gif
Stage 2: https://puu.sh/Bfzvp/78a0563b4d.gif
Stage 3: https://puu.sh/BfzBT/a27dd49b4a.gif

My assumption is whatever settings for the rear brake lights are mixed up between stage 3 and 1, but I'll defer to your knowledge on the subject.

This was not an issue when this code was running on Windows.

Even if you could point my to where that is happening in your code would be helpful!

**Comment by MrDaGree** [comment]
I cannot do anything without your VCF. I'm going to assume the light activation is set to euro or something other than manual or auto. This is a known bug if this is the case.

**Comment by Gibster99** [comment]
I'm assuming you're talking about the one within the config as I'm on V1.1.3a
`vcf_files = {
	"ambulance.xml",
        "dinghy.xml",
        "fbi.xml",
        "fbi2.xml",
        "firetruk.xml",
        "flatbed.xml",
        "police.xml",
        "police2.xml",
        "police3.xml",
        "police4.xml",
	"pranger.xml",
	"sheriff.xml",
	"sheriff2.xml"
`

**Comment by Gibster99** [comment]
Here's a sample of police.xml 
https://pastebin.com/D8HNn0Z7

**Comment by Gibster99** [comment]
Just a note, I copied the files directly from my old server in which this all worked perfectly, the only change made was to the case of the files being referenced. Because it's a linux server now.

**Comment by Gibster99** [comment]
Issue closed, magically fixed itself...
