### ISSUE TITLE
Looking great! 1 Issue

### ISSUE THREAD

**Issue by x0Z3ro0x** [MrDaGree/ELS-FiveM#19]
The new build is looking great. I love the new hud. Anyway not sure if you are aware, but turning on the stages of the sirens cause the lights / other parts of the car to flash. For instance on the police2 the lightbar with go invisible all together. On the police3 a spoiler will appear and disappear even though it has no spoiler by default. This continues across several models.

Hope you get it worked out and thanks for the new dev updates!

**Comment by MrDaGree** [comment]
This is on a streamed vehicle for els?

**Comment by MrDaGree** [comment]
I'm going to assume you have stock vehicles. Please note that you must stream els vehicles. If you do have els vehicles feel free to hop on my discord and Ill help you out in #support.

**Comment by x0Z3ro0x** [comment]
No the first two vehicles we tried was stock vehicles. police and police2. The last car we tried was an addon police Viper. I have not tried on any other vehicles. I will stop in your discord. Thank you for the fast reply and I look forward to your future releases.
