### ISSUE TITLE
ELS on ADDON police cars

### ISSUE THREAD

**Issue by vernietiger** [MrDaGree/ELS-FiveM#26]
Hello, 

When i instal ELS on an ADDON police car or lets say emergency car the AI traffic wont get out of the way like they do for an replace police car 

I hope u can help me

**Comment by MrDaGree** [comment]
Make sure the vehicle has sirens setup

**Comment by vernietiger** [comment]
Yes it has, 

Lights and sirens are working but npc won’t move out of the way when running code 3

**Comment by MrDaGree** [comment]
Are you able to DM me on discord of the resource with the vehicle?

**Comment by vernietiger** [comment]
Sure i can,

Whats you discord tag?

**Comment by MrDaGree** [comment]
MrDaGree#0404

**Comment by vernietiger** [comment]
https://www.dropbox.com/sh/6xihyqlzbke6zti/AAAo_VfIOju0fqArMJj2TTu9a?dl=0 

Here u can find my vehicles en Els config. 
Its with al of my addons: ambulance 2, MUG, VOLVO, SFBC3, WP3 and so on. Pls let me know how to fix it

**Comment by MrDaGree** [comment]
Looking through it I didnt see any carvariations, for sure there is none for the ambulance2.

**Comment by vernietiger** [comment]
So u need an carvariotion for every car? 🤔

**Comment by MrDaGree** [comment]
Yes, if it is an add-on so it has GTAV sirens setup.

**Comment by vernietiger** [comment]
okey thnx, 

I'll make sure that i fix that. If that didn't work i'll let you know :)
