### ISSUE TITLE
ELS occasionally breaks [Client Side]

### ISSUE THREAD

**Issue by Zenoxez** [MrDaGree/ELS-FiveM#27]
**Describe the bug**
I have ELS installed on my server. Occasionally my players will complain that ELS has suddenly stopped working. On each car all of the lights suddenly go dark and stop working, except for the flashing headlights or taillights. This seems to be client side as it will not happen for all clients at the same time. A game restart and occasionally a FiveM client cache clear is required to fix the problem.

**To Reproduce**
It is completely random.

**ELS Information:**
Version #: 1.75
Server Version #: 9.5.8
Screenshots of Config.lua, vcf.lua, vcf folder:
https://gyazo.com/35f194b32d066c92196d8f50d9560f67
https://gyazo.com/6fd47129388bb2ec599b44de634a3728

**Comment by Zenoxez** [comment]
...Hello?

**Comment by Zeemahh** [comment]
Anything appear in your client console? Also, have you tried newer versions released?

**Comment by Zeemahh** [comment]
Try the [latest release](https://github.com/MrDaGree/releases/latest).
