### ISSUE TITLE
CRS (Cruise) aren't working on the lightbar even though controller shows it's turned on. Able to reproduce this on vehicles that have cruise lights. Using ver. 1.75, also present in 1.70

### ISSUE THREAD

**Issue by LinuxWebGeek** [MrDaGree/ELS-FiveM#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**ELS Information:**
Version #:
Server Version #: 
Screenshots of Config.lua, vcf.lua, vcf folder:

**Additional context**

**Comment by MrDaGree** [comment]
Please properly fill out the issue.
