### ISSUE TITLE
CRS (Cruise Light) Not Working

### ISSUE THREAD

**Issue by LinuxWebGeek** [MrDaGree/ELS-FiveM#29]
**Describe the bug:**
Cruise lights are not working even though the panel shows they're activated. Everything else works great.

**Steps to reproduce the behavior:**
I am able to reproduce this with all ELS enabled vehicles by pressing the CRS button.

**Expected behavior:**
When I press the CRS (Cruise Light Button), I expect the cruise lights enabled in the els XML to turn on.

**Screenshots:**
![screenshot1](https://user-images.githubusercontent.com/47883351/53720724-10528180-3e27-11e9-8bd5-144f89fc1b58.jpg)

**ELS Information:**
Version #: 1.75
Server Version #: v1.0.0.1096 win32

Screenshots of Config.lua, vcf.lua, vcf folder:

![config](https://user-images.githubusercontent.com/47883351/53720897-7808cc80-3e27-11e9-8570-451fd93e9018.jpg)

**Comment by MrDaGree** [comment]
Can i get the VCF for the vehicle

**Comment by LinuxWebGeek** [comment]
I have attached 2 different VCF from vehicles I use. I have changed the file extension to .txt so that I can attach the actual files I used.


VCF:
[fbi.txt](https://github.com/MrDaGree/ELS-FiveM/files/2929158/fbi.txt)
[sheriff.txt](https://github.com/MrDaGree/ELS-FiveM/files/2929160/sheriff.txt)

**Comment by UltrAS4F** [comment]
how to download this

**Comment by UltrAS4F** [comment]
tha panel side

**Comment by Zeemahh** [comment]
> how to download this

Uh? Why are you commenting on this issue with some random question..?

**Comment by mrquentinh** [comment]
No fix for this bug ? I have the problem too...

**Comment by MrDaGree** [comment]
Cruise lights never have been fully implemented thus the panel shows that they are "on" but you say they arent and are "broken"
