### ISSUE TITLE
[New installed] Outdated 

### ISSUE THREAD

**Issue by magnus505** [MrDaGree/ELS-FiveM#3]
---------- ELS (master Build) by MrDaGree ----------
           Current Version: 1.1.3a
           Newest Version: 1.1.3a
 
 
---------- Outdated ----------
 
  CHANGES: 
- Github change
 
 
  Whats the point of putting something funny
             if its not even funny?
-------------------------------------------------

**Comment by MrDaGree** [comment]
I know. It really has no issues.
