### ISSUE TITLE
Random FPS Drop

### ISSUE THREAD

**Issue by nejccifer** [MrDaGree/ELS-FiveM#30]
**Describe the bug**
Random FPS Drops. So essentialy, my graphics card is GTX 970 and ELS works perfectly fine for me on our FiveM server. But then for some reason, other people with graphic cards GTX 1080 ti and stuff like that experience up to 50FPS drop when the sirens are turned on. The more vehicles with sirens that there are the more FPS drop will happen. We all have same/similar seetings for GTA V (Everything to max) so I don't understand why this is happening

**To Reproduce**
I don't think that every single person can reproduce this, but if you wish to try, all you have to do is spawn one or more ELS vehicles and turn on the sirens. The more you spawn the bigger FPS drop.

**Expected behavior**
I hope that someone will be able to help me and make the FPS drop thing dissaper. Cause we really want to use ELS, but we just can't afford it if many players will get max 15 FPS around emergency vehicles.

**Screenshots**
Sadly I don't have screenshots, as this thing doesn't happen to me, but there is nothing much to see. It's a common FPS drop, so everything just becomes really laggy.

**ELS Information:**
Version 1.1.3a & 1.75 (tested on both and same results):
Server Version Linux build: 1052-5263e3d13eacecd18cdf7541fe04458b12bbdfd
Screenshots of Config.lua, vcf.lua, vcf folder:
![config](https://user-images.githubusercontent.com/16784435/54045073-e99e9d00-41d0-11e9-82d7-83b720c669e8.png)
![vcffolder](https://user-images.githubusercontent.com/16784435/54045321-937e2980-41d1-11e9-9b8d-0324e79591a2.png)

I currently don't have access to vcf.lua, since we decided to try the latest stable release, which is 1.1.3a and this one doesn't have vcf.lua file

**Additional context**
Like I said, the problem doesn't seem to be quality of graphics card, etc. Since it works perfectly fine for my GTX 970 while it's destryoing my friend's FPS on his GTX 1080 ti. GTA V graphics settings are the same or very similar.

**Comment by AL-RP** [comment]
I have the same issue for my server.

**Comment by rwhat** [comment]
FPS drop is common, as the script uses more resources when more vehicles are on running code. This is going to a per client issue, as the same goes for when ppl lose textures, it becomes a client issue not everyone will have the issue. You can experience for drop also depending on how many scripts you have how poorly written scripts are as well.

**Comment by Zeemahh** [comment]
Since this, commits have been made to optimise the script. You should try these out!
