### ISSUE TITLE
ELS fivem - remove Y, L from panel

### ISSUE THREAD

**Issue by PepapapZdepaa** [MrDaGree/ELS-FiveM#31]
i tried to edit your code to remove useless buttons for our server. 
We only want to keep 1,2,3 sirens and Q on panel?
is there any way you can edit it and send it to me?

**Comment by MrDaGree** [comment]
Define useless. Everything in els is required for the pattern changes etc.

**Comment by PepapapZdepaa** [comment]
i mean we dont need those .
we only need Q, 1,2,3 in pannel

**Comment by MrDaGree** [comment]
Try luxart then. This is for els with patterns
