### ISSUE TITLE
When i have the ELS script on my server the headlights on the cars with ELS just keeps blinking like if the emergency lights was on, but they are not.

### ISSUE THREAD

**Issue by helpme1234556** [MrDaGree/ELS-FiveM#37]
When i have the ELS script on my server the headlights on the cars with ELS just keeps blinking like if the emergency lights was on, but they are not. When I turn it off it sould not still be blinking

**Comment by MrDaGree** [comment]
Known issue if you are using the 'EURO' style of light activation
