### ISSUE TITLE
Control panel disapears

### ISSUE THREAD

**Issue by marcos-acpc** [MrDaGree/ELS-FiveM#38]
**Describe the bug**
Every time I leave a police car for the 1st time the UI control panel on corner disapears and never shows up

**To Reproduce**
spawn a car and try
**Expected behavior**
I was the UI control panel would keep on screen while in the car
**Screenshots**

**ELS Information:**
Version #:last stable one from github
Server Version #: dont know
Screenshots of Config.lua, vcf.lua, vcf folder:

**Additional context**

**Comment by MrDaGree** [comment]
vcf to the vehicle and screenshots of the error in the f8 console?

**Comment by marcos-acpc** [comment]
no errors on the console and is is vcf to the vehicle

**Comment by MrDaGree** [comment]
Where _is_ the vcf?

**Comment by marcos-acpc** [comment]
![image](https://user-images.githubusercontent.com/47359588/57405226-ce9ed800-71d5-11e9-912b-ba89b2b42fa7.png)
![image](https://user-images.githubusercontent.com/47359588/57405636-dd39bf00-71d6-11e9-9cc0-5886b9cf4d73.png)
![image](https://user-images.githubusercontent.com/47359588/57405735-16722f00-71d7-11e9-8d60-ba7145e4bf4f.png)

**Comment by JHodgson1** [comment]
>https://github.com/MrDaGree/ELS-FiveM/issues/38#issuecomment-490569065

Did you enable any config option for that to show? That isn't intended to always show.

**Comment by MrDaGree** [comment]
Theres no color set in extra 10 in the vcf. try adding color to that as I don't remember if it automatically adds something in

**Comment by marcos-acpc** [comment]
JHodgson1, not really the only thing I have done was to add all the vcf and set the offset so it would not stay on top of the speedo
 here you have my config:
![image](https://user-images.githubusercontent.com/47359588/57435999-b6ab7080-7236-11e9-927b-46ba1c70dfd5.png)

**Comment by marcopaggioro** [comment]
I have the same problem. How did you solve?

**Comment by Zeemahh** [comment]
Try the [latest release](https://github.com/MrDaGree/ELS-FiveM/releases/latest). I'm pretty sure I fixed this in a commit.
