### ISSUE TITLE
Siren lights never fully turned off

### ISSUE THREAD

**Issue by MoravianLion** [MrDaGree/ELS-FiveM#41]
Hi, after renewing my server with newer artifacts (otherwise no change for ELS, which has been working fine till now), I can't turn of siren lights completely. There are always at the first setup of the chosen lighting pattern. Never fully turned off. V 1.1.3a

```
Error resuming coroutine: @ELS-FiveM/client/client.lua:412: attempt to index a nil value (field '?')
stack traceback:
@ELS-FiveM/client/client.lua:412: in function 'setExtraState'
@ELS-FiveM/client/client.lua:1659: in function <@ELS-FiveM/client/client.lua:1650>
Error resuming coroutine: @ELS-FiveM/client/client.lua:412: attempt to index a nil value (field '?')
stack traceback:
@ELS-FiveM/client/client.lua:412: in function 'setExtraState'
@ELS-FiveM/client/client.lua:1618: in function <@ELS-FiveM/client/client.lua:1611>
```

Stuck at this static light setup, when it should be off.

![static](https://user-images.githubusercontent.com/38085706/57644007-0d0c0c80-75b3-11e9-841e-4150aac960e8.png)

**Comment by MoravianLion** [comment]
Ok, even weirder discovery - on my test server, which is exact copy, I don't have this problem...

**Comment by MoravianLion** [comment]
Ok... Restarting the script helped O.o

**Comment by Zeemahh** [comment]
Try latest version, let me know if this still persists.
