### ISSUE TITLE
no sound siren for others

### ISSUE THREAD

**Issue by TomTheHunter** [MrDaGree/ELS-FiveM#44]
So basically i put my addon car to my server. I want that  addon to have els lights but no siren sounds.

so i did this.

 `  <SOUNDS>
        <MainHorn InterruptsSiren="true" AudioString="SIRENS_AIRHORN" />
        <ManTone1 AllowUse="true" AudioString="" />
        <ManTone2 AllowUse="true" AudioString="" />
        <SrnTone1 AllowUse="true" AudioString="" />
        <SrnTone2 AllowUse="true" AudioString="" />
        <SrnTone3 AllowUse="true" AudioString="" />
        <SrnTone4 AllowUse="true" AudioString="" />
        <AuxSiren AllowUse="true" AudioString="" />
        <PanicMde AllowUse="true" AudioString="" />
    </SOUNDS>`

i dont hear it (thats perfect!!!) but everyone else can.

how can i mute that siren for others but not for only me!!

is that bug??

**Comment by MrDaGree** [comment]
Set AllowUse to false or change the vehicle class to something other than emergency
