### ISSUE TITLE
Automatically repaired the engine

### ISSUE THREAD

**Issue by Valkatastz** [MrDaGree/ELS-FiveM#45]
**Describe the bug**
When the vehicle is being damaged without the sirens and engine breaks down, it cannot go anymore until a mechanic comes and repair it. However, when the lights are turned on, the engine is like brand new.

**To Reproduce**
Same as the description. Turn them off, crash until the engine breaks down and turn the lights on -> brand new engine until the lights are on and car can still go.

**Expected behavior**
Brand new engine on lights on every single time the engine breaks down.

**Screenshots**

**ELS Information:**
Version #: 1.75
Server Version #: 6.2.2
Screenshots of Config.lua, vcf.lua, vcf folder:
![Config.lua](https://i.imgur.com/B0MnBwL.png)

Haven't changed anything to any of the files.

**Additional context**

**Comment by MrDaGree** [comment]
Please search for the issue first and you'd know I cannot fix this as it's an issue with GTA itself.

**Comment by ColbyMMMM** [comment]
is not a gta issue tho how can lspdfr els  can just fine on fivem

**Comment by MrDaGree** [comment]
Then you can fix it if you believe its not a GTA issue. SP ELS does client-side memory editing to make it not repair itself, something I cannot do with FiveM.
