### ISSUE TITLE
ELS not working on 64 slots with OneSync

### ISSUE THREAD

**Issue by Askor16** [MrDaGree/ELS-FiveM#46]
**Describe the bug**
Today we changed our server to 64 slots version, with onesync, it always worked fine since today when we changed the version. Now the menu works and it changes the lights with Q keys but the lights doesn't turn on. 

**To Reproduce**
I get into the car, the ELS menu appears, i click Q key to switch to light pattern, the siren buttons switch and turns on but anything more happends, the lights never turns on.

**Expected behavior**
When I click the Q key the lights should turn on.

**ELS Information:**
Version #: 1.75
Server Version #: FiveM/OneSync-ALPHA
Screenshots of Config.lua, vcf.lua, vcf folder:
![image](https://user-images.githubusercontent.com/51933762/59643199-02bbd000-9168-11e9-87f1-405f059c503e.png)
![image](https://user-images.githubusercontent.com/51933762/59643206-0d766500-9168-11e9-8b72-bdbdb1abda9a.png)
![image](https://user-images.githubusercontent.com/51933762/59643217-1b2bea80-9168-11e9-8840-728ca008822c.png)

**Comment by MrDaGree** [comment]
ELS doesnt rely on amt of players to operate and I do not have access to OneSync to test it more so. Unless anyone else has the ability to confirm this I will close it in a week.
