### ISSUE TITLE
Wrong sirens on vehicles

### ISSUE THREAD

**Issue by subtraho** [MrDaGree/ELS-FiveM#47]
Hey,
 i've been looking for this part but couldn't find it anywhere but how do i change what sirens play per vehicle. As i see it now ELS is configured to always play the police sirens except for siren3 (the warning siren in the els menu). Can this be changed because changing this in the XML files doesn't work. 

For example once i have an ambulance and choose siren option 1 or 2 it plays police sirens instead of ambulance sirens. The same thing happens with a firetruk. 

I just want police vehicles to play police sirens, police bikes police bike sirens, firetrucks firetruck sirens, ambulance ambulance sirens (u know where im going to......) 

Again does someone know a fix for that or does it still need to be implemented and if so, how can this be done???

Thanks in advance,
-subtraho

**Comment by MrDaGree** [comment]
What version are you on?

**Comment by subtraho** [comment]
I'm on version 1.13a

**Comment by MrDaGree** [comment]
They cant be changed on that version easy. Anything higher allows changes through the vcf. Just have to find the correct string hash to the ambulance sounds.

**Comment by subtraho** [comment]
so if i get 1.75 for example i can change the firetruck sirens in the vcf and they will play like they should in fivem?

**Comment by MrDaGree** [comment]
if you have the correct sound hash. All the ones I've been able to find do not work as why 1.1.3 only played police sounds.

**Comment by subtraho** [comment]
OMG THANK U SO MUCH. IM SO STUPID XD.

Version 1.75 fixed it for me after changing the hashes in the vcf file.
i've been stuck on this for so long!!

Again thank u very much and u have an awesome plugin!
