### ISSUE TITLE
Toggle issue and panel issue since most recent FiveM Update

### ISSUE THREAD

**Issue by RichardBiggs** [MrDaGree/ELS-FiveM#48]
**Describe the bug**
The first issue is that the lighting panel flashes anytime signal 1 - 3 are active

The second issue is that when toggling the lights off the remain on for what seems to be a random amount of time, sometimes briefly sometimes longer.
**To Reproduce**
Issue 1: Toggle any signal 1-3 on and have control panel visible

Issue 2: Toggle through signals within an els vehicle
**Expected behavior**
Issue 1: While signals are active or inactive and panel is enabled I expected the panel to remain statically visible

Issue 2: Expected lights to cease when toggled off
**Screenshots**

**ELS Information:**
Version #:1.75
Server Version #: 1380-0b3915618c6cc278c2457ea93775255ed41e49c3
Screenshots of Config.lua, vcf.lua, vcf folder:
VCF Folder: https://gyazo.com/32375032ee6cfdda044361dc388d00fe
vcf.lua: https://gyazo.com/c08be699c34d3d591542d0f1ec5bb1be
Config.lua: https://gyazo.com/efc7932b0436243b8c2d0be896845cae

**Additional context**
I have ran this script since April of 2019 with no issues, these issues recently appeared after a long list of FiveM client and server updates. I appreciate any help in resolving this issue. If a video of the actions would be helpful I will gladly comply.

Thank you for your time and please have a wonderful day,

Rich Biggs
Discord info for further contact if necessary: Rich Biggs#6564

**Comment by TheSleepyFuck** [comment]
I have the exact same issue. It started last night after a server restart for no reason.

It must be the new update -_-

**Comment by 89537kay3** [comment]
I have the same issue and after checking the FiveM code, it appears this update: https://gyazo.com/b5a7b7b21c267175d7e7dbd819c9fea4 is causing the issue. I've spoke to MrDaGree and he's aware

**Comment by RichardBiggs** [comment]
Seems today's FiveM client update has resolved the flickering panel, however the delay after turning signals off seems to persist.

**Comment by Vi-Initiate-25** [comment]
Im have the same issue, however the most recent FiveM update didn't resolve it.

**Comment by Archerfy** [comment]
On today i also have the same issue.
But i also have that i can not switch between stages.

**Comment by Zeemahh** [comment]
Guessing this is no longer relevant due to no additional issues than this. Plus it’s ~5 months old.
