### ISSUE TITLE
problem when I get off the vehicles

### ISSUE THREAD

**Issue by nitross66** [MrDaGree/ELS-FiveM#49]
**Describe the bug**
hello radio problem

**To Reproduce**
that's when I run my server and I spawn a vehicle everything is fine, it works well but the times when I get off the vehicle and I go back everything disappears and when I press the button it puts me the game radio instead control of the lights

**Expected behavior**
I was expecting to get back in the car is that everything works well considering that its march at the beginning

**Screenshots**
sorry I do not know or take the screen

**ELS Information:**
Version #:
Server Version #: 
Screenshots of Config.lua, vcf.lua, vcf folder:

**Additional context**

**Comment by nitross66** [comment]
Hellor error  scripterror @els-fivem/client/client.lua:376:attempt to index a nil value

**Comment by MrDaGree** [comment]
It's because the vehicle is missing vital information in the vcf that the script requires. For this instance it's the header color.

**Comment by nitross66** [comment]
sorry i did not understand but it's nice to have try to help me i search everywhere or something was missing but i did not find

**Comment by MrDaGree** [comment]
You would not find it as it is _missing_, it would be in the top of the vcf file for the _interface_.
