### ISSUE TITLE
sheriff xml file not working

### ISSUE THREAD

**Issue by Waddell34** [MrDaGree/ELS-FiveM#50]
when i spawn the sheriff no light control and the radio comes on

**Comment by MrDaGree** [comment]
I can't help without the information requested when you make these.

**Comment by Waddell34** [comment]
When I spawn the sheriff's car slot on my server the light control panel
doesn't come up and the lights won't turn on I don't know if it's is the
xml or something

**Comment by Waddell34** [comment]
Sorry but I can't get the sheriff lights to work with the 1.75 ELS-FimeM-master

**Comment by MrDaGree** [comment]
I need information on how you have it configured. That's why the questions for issues are important

**Comment by Waddell34** [comment]
The xml is the way I downloaded it from get hub

**Comment by Waddell34** [comment]
The xml is the sheriff xml that is in the ELS vcf folder from your up load

**Comment by Zeemahh** [comment]
> The xml is the sheriff xml that is in the ELS vcf folder from your up load

By default, the preset `SHERIFF.xml` file isn't loaded. If you wish to use it, add it to the `vcf_files` table in `vcf.lua`.
