### ISSUE TITLE
Other passengers can control lights

### ISSUE THREAD

**Issue by velotoxicsounds** [MrDaGree/ELS-FiveM#52]
Hello

unfortunately, other passengers in the car can also control the lamps. Is it possible to enter a setting in the configuration that only the driver of the vehicle can control the lamps?

**Comment by Zeemahh** [comment]
This was caused because of a slight oversight when a performance-related PR was created back in April. I forgot to check if ped was in seat `-1` (driver) or `0` (front passenger).

This is now fixed in #53

**Comment by Zeemahh** [comment]
[Version 1.9](https://github.com/MrDaGree/ELS-FiveM/releases/1.9) contains this fix.
