### ISSUE TITLE
My els is "stopping" so the els menu goes away and sirens no longer work, if they were turned on they get stuck.

### ISSUE THREAD

**Issue by Anaaliasteroidi** [MrDaGree/ELS-FiveM#54]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**ELS Information:**
Version #:
Server Version #: 
Screenshots of Config.lua, vcf.lua, vcf folder:

**Additional context**

**Comment by Zeemahh** [comment]
![](https://i.imgur.com/3HzMeO6.png)
