### ISSUE TITLE
ELS stops working after sometime

### ISSUE THREAD

**Issue by Anaaliasteroidi** [MrDaGree/ELS-FiveM#55]
**Describe the bug**
My els is "stopping" so the els menu goes away and sirens no longer work, if they were turned on they get stuck.
**To Reproduce**
Just having 30+ players on server and it "crashes"
**Expected behavior**
i expect it to work
**Screenshots**
![image](https://user-images.githubusercontent.com/59299624/71537748-49fdf700-2929-11ea-9eba-5dcd09e07413.png)
![image](https://user-images.githubusercontent.com/59299624/71537751-51bd9b80-2929-11ea-9399-98665c3ec0a8.png)

**ELS Information:**
Version #:1.9
Server Version #:  1903
Screenshots of Config.lua, vcf.lua, vcf folder:
![image](https://user-images.githubusercontent.com/59299624/71537783-b678f600-2929-11ea-9071-624298a546cd.png)
![image](https://user-images.githubusercontent.com/59299624/71537793-c5f83f00-2929-11ea-8358-ef50bc0a7014.png)

**Additional context**

**Comment by Zeemahh** [comment]
After checking the code and attempting to reproduce this, I was unsuccessful. Only thing I can think of is some weird case based on local ID for the vehicle mismatching across clients. Without doing too much work, a condition for network session state should suffice here. Which will be present in master shortly.
