### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Richards0nd** [MrDaGree/ELS-FiveM#57]
### Bug Description
I noticed that there is an error in the script!
All cars added to the ELS system when they crash they fix automatically!
But this only when someone is inside the vehicle along with the motorcycle!
So if you have 2 people in the car, and the driver crashes it, the car for the passenger is fixed automatically!
For the driver he does not agree on how long he is in the car, after he gets out and the person who was in the car along with him gets in, the car for the driver automatically fixes!
I did all these tests all day, removed several scripts and in the end this error was from ELS!
I tried using old versions but it didn't solve ...
I'm leaving my ELS configuration files from both an old version (It's in the folder like: ELS-Fivem) and the new version (It's in the folder like: ELS-FiveM-new-old)

### Reproductive Steps
-

### Expected Behavior
-

### Screenshots
-

### ELS Information
* Version: 1.8 and 1.9
* Server Version: 1972
* Screenshots of config.lua, vcf.lua, vcf folder:
https://uploads.richardsondouglas.com.br/mstsc_XMaFQxM9m2.png
https://uploads.richardsondouglas.com.br/mstsc_AaClLUW0y7.png
https://uploads.richardsondouglas.com.br/mstsc_eBnEkwvsgK.png

### Additional Information
https://uploads.richardsondouglas.com.br/ELS-FiveM.zip

**Comment by Zeemahh** [comment]
According to this native here:
https://github.com/MrDaGree/ELS-FiveM/blob/master/client/client.lua#L645

This issue shouldn't exist, are you sure you're on the latest version?

**Comment by Richards0nd** [comment]
The versions I tested were these: 1.8 and 1.9
And both have this problem ...

**Comment by Zeemahh** [comment]
I don't know what your error is since you never actually provided it, but try https://github.com/MrDaGree/ELS-FiveM/releases/tag/1.91
