### ISSUE TITLE
Possible Issue: All lightbars just seem to flicker

### ISSUE THREAD

**Issue by Lxk3y** [MrDaGree/ELS-FiveM#58]
### Bug Description
When adding any ELS car to FiveM, the lightbars just seem to flicker there pattern, as opposed to properly displaying there pattern

### Reproductive Steps
Spawn in an ELS car and use the lights

### Expected Behavior
Lightbars to produce the normal pattern for the XML file, rather than just flicker randomly

### Screenshots
N/A

### ELS Information
* Version #:1.9
* Server Version #: FXServer-master v1.0.0.1972 linux
* Screenshots of config.lua, vcf.lua, vcf folder:

**VCF Folder**
![image](https://user-images.githubusercontent.com/47719567/72224969-f1a93500-3577-11ea-837e-55d99b95ad1e.png)

**vcf.lua**
![image](https://user-images.githubusercontent.com/47719567/72224979-0c7ba980-3578-11ea-916b-745afdd9c8ee.png)

**Config.lua**
![image](https://user-images.githubusercontent.com/47719567/72224988-1d2c1f80-3578-11ea-978b-f7455093a25e.png)

**Comment by RevTheDev** [comment]
Got the same issue happens with all els car iv tried and the just seem to flicker like there constantly on or the flash really slow like they don’t have a pattern

**Comment by MrDaGree** [comment]
Have you tried changing the light and flash delays in the console?

**Comment by Lxk3y** [comment]
No i havent but im glad it isnt just me

**Comment by RevTheDev** [comment]
Yeah didn’t think of that I’ll give that go

**Comment by MrDaGree** [comment]
Most the time this is due to a lot of resources running or low processor speeds. I believe FPS syncing should be in effect but Ill have to double-check. Just note a CPU running at 3.4Ghz is going to produce a different result than 4.0Ghz.

**Comment by RevTheDev** [comment]
It’s a 3.7Ghz cpu that my server uses

**Comment by MrDaGree** [comment]
^ Client as the flashing is client side.

**Comment by RevTheDev** [comment]
Ah well my pc is 3.9ghz

**Comment by RevTheDev** [comment]
This what my lights are doing https://streamable.com/6k2bg

**Comment by Lxk3y** [comment]
Same @RevTheDev exactly the same

**Comment by MrDaGree** [comment]
That looks normal?

**Comment by Lxk3y** [comment]
I can assure you that isnt normal. Every car has the same, flickery light pattern. It isnt even a pattern its just, a mess of random lights

**Comment by RevTheDev** [comment]
it might be the cars I’m putting in some different cars that are more up to date and see what they do

**Comment by MrDaGree** [comment]
> I can assure you that isnt normal. Every car has the same, flickery light pattern. It isnt even a pattern its just, a mess of random lights

I mean I made it so I think I know normal. Have you tried changing the pattern?

**Comment by RevTheDev** [comment]
https://streamable.com/5nse7
It’s like there flashing too fast This car I have u can see it has its flash patterns just it’s like there going light speed aha

**Comment by MrDaGree** [comment]
then change the config variables like mentioned above?

**Comment by RevTheDev** [comment]
Yeah got thank you 🙏 with a bit of tweaking the light delay and flash it slowed it down a bit then pressing 8 I can cycling through the patterns there are still some fast one but I think that what the pattern are like but doing the delay and flash did the trick the lights are bright yeah that’s coz I’m working on my visual settings still aha
https://streamable.com/p73z1
