### ISSUE TITLE
Another case of ELS "Crashing"

### ISSUE THREAD

**Issue by rubbertoe98** [MrDaGree/ELS-FiveM#59]
### Bug Description
One of these variables is nil in line 606, causing the thread to break. 
`MainThrd/ ^1SCRIPT ERROR: @els3/client/client.lua:606: attempt to index a nil value (field '?')^7`
### Reproductive Steps
Use ELS consistently in a high pop server for > 15mins
### Expected Behavior
Not for thread to break so ELS continues working

### Screenshots
N/A

### ELS Information
Latest

**Comment by Zeemahh** [comment]
Try https://github.com/MrDaGree/ELS-FiveM/releases/tag/1.91

**Comment by rubbertoe98** [comment]
Ah my bad, thought we were on that one. Will report back if issue continues, seems ok for now

**Comment by rubbertoe98** [comment]
Found another case of a similar issue (using latest 1.91)
`MainThrd/ ^1SCRIPT ERROR: @els3/client/client.lua:650: attempt to index a nil value^7`

**Comment by Zeemahh** [comment]
Okay, I’m gonna look into this since something clearly has messed up along the history of this file. Yes, we can create a workaround for this by adding a check if the index isn’t nil, but that’s not a fix, and doesn’t find the root cause for the issue.

**Comment by rubbertoe98** [comment]
I agree, but I think a nil check should be added for now until the root issue is found as it is rather "resource-breaking". The only fix is to relog, since you can't restart the thread.

**Comment by Zeemahh** [comment]
> but I think a nil check should be added for now until the root issue is found as it is rather "resource-breaking"

Now implemented in master, will replace 1.91 rar now.
