### ISSUE TITLE
Force Patterns Not Working

### ISSUE THREAD

**Issue by nap14hockey** [MrDaGree/ELS-FiveM#61]
### Bug Description

After Adding "forced patterns" in the VCF, and updating the file, they don't work
### Reproductive Steps

Change forced patterns options in VCF, upload, and restart
### Expected Behavior

The stage change should change the pattern

### ELS Information
* Version #: 1.92 
* Server Version #1.0.0.2083:

**Comment by MrDaGree** [comment]
Who said this was actually implemented yet?
