### ISSUE TITLE
Error, ELS doesn't quite work either

### ISSUE THREAD

**Issue by larscrazynl** [MrDaGree/ELS-FiveM#64]
The error in my console if i use ELS vehicle:

ELS ERROR FROM CLIENT
PLAYER NAME: Raoul
PLAYER ID: 2
ERROR: SCRIPT ERROR: @ELS-FiveM/client/client.lua:431: attempt to index a boolean value

**Comment by Danny9865** [comment]
same issue

**Comment by Zeemahh** [comment]
As per `master`, the line mentioned doesn't index. So, please try the [latest release](https://github.com/MrDaGree/ELS-FiveM/releases/latest) and see if this error still occurs. If so, please let us know by posting the error again which will contain a reliable line in the code.

**Comment by Danny9865** [comment]
![image](https://user-images.githubusercontent.com/58650168/86182051-1c3b7a00-bb27-11ea-8f46-5618d5111c94.png)

just spams this for me mate, im sure im using the latest

**Comment by Danny9865** [comment]
or this

![image](https://user-images.githubusercontent.com/58650168/86182239-7c322080-bb27-11ea-8a47-491eccb1c21d.png)

**Comment by Zeemahh** [comment]
The first error seems to be some case where the vehicle model cannot be found within a list of 'all known models'. Which is weird. Are you running OneSync Infinity?

**Comment by Danny9865** [comment]
nah im running just onesync 96 slot server, at least with that information i roughly know where to look so il do some digging, also at least i know its something i've fucked up so il look into it

**Comment by Danny9865** [comment]
by index a boolean value, this being a true or false statement, is this saying there shouldn't be a true or false statement, or just that its wron ie it says false when it should be true?

**Comment by Zeemahh** [comment]
Hi, please see issue https://github.com/MrDaGree/ELS-FiveM/issues/90#issuecomment-732083440.
