### ISSUE TITLE
Error on line 431

### ISSUE THREAD

**Issue by Will3126** [MrDaGree/ELS-FiveM#66]
Error: Script Error: @els/client/client.lua:431: attempt to index a bollean value.
Any idea why I am getting this?
![image](https://user-images.githubusercontent.com/40750425/76704701-ce4e5380-66a8-11ea-9ccb-a2d0b5c3320f.png)

**Comment by MrDaGree** [comment]
Can you send a screenshot of your config?

**Comment by Will3126** [comment]
Yeah here you go 
![image](https://user-images.githubusercontent.com/40750425/76715569-e8b11d00-66fa-11ea-9780-75d829db3ef1.png) 
![image](https://user-images.githubusercontent.com/40750425/76715572-eea6fe00-66fa-11ea-8d58-6610469235d9.png) If you need anything else just let me know!

**Comment by MrDaGree** [comment]
It seems like for whatever reason the vehicle giving that error has no header colors set in the VCF

**Comment by Will3126** [comment]
Hm, Alright thanks for the help!
