### ISSUE TITLE
the lights on the cars despawn and spawn again every time i turn on the lights

### ISSUE THREAD

**Issue by victortiger3000** [MrDaGree/ELS-FiveM#68]
### Bug Description

when you turn on the lights the lightbar/every extras despawn and spawn when you have the lights on

### Reproductive Steps

every time i turn on the lights they do it

### Expected Behavior

they despawn

### Screenshots

https://cdn.discordapp.com/attachments/541622280753643522/700043223938105534/light.PNG
https://cdn.discordapp.com/attachments/541622280753643522/700043239096320060/light3.PNG
https://cdn.discordapp.com/attachments/541622280753643522/700043245136379976/light2.PNG

### ELS Information
* Version #:  try every
* Server Version #:  https://cdn.discordapp.com/attachments/541622280753643522/700044773125521520/hallo.PNG
* Screenshots of config.lua, vcf.lua, vcf folder: https://cdn.discordapp.com/attachments/541622280753643522/700043998458413136/vcf2.PNG
https://cdn.discordapp.com/attachments/541622280753643522/700043996113666066/vcf.PNG

**Comment by MrDaGree** [comment]
That first screenshot isn't related to els. The panel shows that the extras are enabled. Are you sure that it's an els vehicle?

**Comment by victortiger3000** [comment]
yes

**Comment by MadLad1Clip** [comment]
Having the same prob mod is running HUD works but roof lights despawn

**Comment by MadLad1Clip** [comment]
I was missing the ELS cars, found some and solved my problem, but i noticed a problem with 1.95 with light reflections not working and after reverting to 1.75 the lights all work now.

**Comment by Zeemahh** [comment]
Hi, please see issue https://github.com/MrDaGree/ELS-FiveM/issues/90#issuecomment-732083440.
