### ISSUE TITLE
Lights never stop

### ISSUE THREAD

**Issue by pavpd** [MrDaGree/ELS-FiveM#69]
### Bug Description
When i spawn car-everything is okay and not blikning. When i change modes 4 times (pressing Q) and then i want to stop light bar- it stops but my backlights are always blinking. I cant stop them anyway... they are always blinking but with different patterns. Only when i spawn car- they are turned off. Siren is same.

### Reproductive Steps
1. Spawn car
2. Press 4 times Q
3. Back lights are always blinking

### Expected Behavior
Not blinking- set in neutral position. Its kind of out of sync.

### Screenshots
Video-https://youtu.be/dGf6Jr-Rpvk

### ELS Information
* Version #: 1.92
* Server Version #: v1.0.0.2345 win32
* Screenshots of config.lua, vcf.lua, vcf folder:
https://i.imgur.com/sA3027t.png
https://i.imgur.com/mONS5gt.png
https://i.imgur.com/Av7jNaw.png

**Comment by Zeemahh** [comment]
There is evidently some sort of issue causing a thread to end. Please provide screenshots or the files relative to your client log when such a thing happens.

**Comment by Zeemahh** [comment]
Hi, please see issue https://github.com/MrDaGree/ELS-FiveM/issues/90#issuecomment-732083440.
