### ISSUE TITLE
bad argument #1 to 'strfind'

### ISSUE THREAD

**Issue by FBFezz** [MrDaGree/ELS-FiveM#77]
### Bug Description
On server startup i get this error

### Expected Behavior
Shouldnt be getting the error on startup

### Screenshots
![image](https://user-images.githubusercontent.com/43589668/86414794-ee883980-bcbc-11ea-82a7-98dcca1cd296.png)

### ELS Information
*Script Version*: https://github.com/MrDaGree/ELS-FiveM/tree/1.93
* Server Version #: "version" is "FXServer-master v1.0.0.2567 linux"
* Screenshots of 
config.lua 
![image](https://user-images.githubusercontent.com/43589668/86414889-36a75c00-bcbd-11ea-9167-d43b8193c32a.png)

vcf.lua 
![image](https://user-images.githubusercontent.com/43589668/86414898-3f982d80-bcbd-11ea-916d-e1e987297235.png)

vcf folder:
![image](https://user-images.githubusercontent.com/43589668/86414916-4aeb5900-bcbd-11ea-8336-1abf2058c785.png)

**Comment by FRRRRICARDOO** [comment]
This error is happening to me too, what can it be?

**Comment by FBFezz** [comment]
Just got it on my localhost as well (windows latest build) with same error and haven't touched the els or cars

**Comment by Zeemahh** [comment]
Oh, right. This is because of the change in file structure. The request for version checking is returning 404.

**Comment by FRRRRICARDOO** [comment]
> Oh, right. This is because of the change in file structure. The request for version checking is returning 404.
And what are we going to do?

**Comment by Zeemahh** [comment]
It's not problematic, is it? Should only show once every 1hr.

**Comment by Zeemahh** [comment]
This is fixed. A patch was applied to ensure this doesn't happen again in the future and a monkey-patch to prevent older versions from erroring - but, on this note, you should be updating whenever possible.

If there is anything that you think could be improved with the updating process, please let me know by creating a separate issue or using the Discord server provided in the README.

Thank you,
Zeemah.

**Comment by FBFezz** [comment]
Is the latest not a dev branch?

**Comment by Zeemahh** [comment]
> Is the latest not a dev branch?

`master` is stable, new releases are automatically created when big/important changes are pushed to the branch. Any 'dev' branch will be just prefixed with 'fix'/'dev'/'tweak' etc to ensure no regressions are introduced and bugs are fixed before it goes onto master.

**Comment by Zeemahh** [comment]
Hi, please see issue https://github.com/MrDaGree/ELS-FiveM/issues/90#issuecomment-732083440.
