### ISSUE TITLE
Lights does'nt reflect

### ISSUE THREAD

**Issue by NeyZzO** [MrDaGree/ELS-FiveM#80]
Hi I have a question when i put some vcf the brightness of the lights is really low we literrally can't see lights can someone help me please 

`Thanks```

**Comment by MrDaGree** [comment]
Install visual mods. light brightness has nothing to do with els.

**Comment by NeyZzO** [comment]
Yeah i know but the problem IS n'ont here thé brightness of the lights is very very very low what Can i do ?
