### ISSUE TITLE
Issue with Resource

### ISSUE THREAD

**Issue by xMRADesignsx** [MrDaGree/ELS-FiveM#82]
### Bug Description
The resource on FiveM is stating that it cannot load a 'meta' data because of the resource file

### Screenshots
![image](https://user-images.githubusercontent.com/66953319/87951400-6f5a7a00-caa0-11ea-8079-d5c65543ed98.png)

### Resource Screenshot
![image](https://user-images.githubusercontent.com/66953319/87951661-bba5ba00-caa0-11ea-96ba-3f84bf568a0d.png)
![image](https://user-images.githubusercontent.com/66953319/87951734-dd06a600-caa0-11ea-9660-7129719a9dd5.png)

**Comment by Zeemahh** [comment]
End-user issue. ELS runs fine out of the box.
