### ISSUE TITLE
Index for current vehicle (CARNOTFOUND) was nil (invalid), returning.

### ISSUE THREAD

**Issue by JustSteijn25** [MrDaGree/ELS-FiveM#85]
### Bug Description
So, In my server I use this ELS for about one month now and i keep getting this error. I've alredy tried to fix it by myself. Here is the error that shows up in F8:

(client) ELS-FIVEM Index for current vehicle (CARNOTFOUND) was nil (invalid), returning.
(client) ELS-FIVEM  Insufficient VCF information obtained for 7481346, returning.

So when this shows up, the lights on the car freezes and doesn't work anymore. Then you need te restart the ELS to let it work again.

### Reproductive Steps
I checked all the XML files but didn't fine any issues.

### Screenshots
![image](https://user-images.githubusercontent.com/64039885/95085335-5d8f8700-071f-11eb-808a-82b4b09c7b6d.png)
![image](https://user-images.githubusercontent.com/64039885/95085403-78fa9200-071f-11eb-9aa4-a4186a8b0e05.png)

### ELS Information
* Version #: 1.92
* Server Version #: v1.0.0.2972
* Screenshots of config.lua, vcf.lua, vcf folder:

Config.lua:
![image](https://user-images.githubusercontent.com/64039885/95085696-de4e8300-071f-11eb-8b2f-164993533f55.png)
![image](https://user-images.githubusercontent.com/64039885/95085730-e9a1ae80-071f-11eb-857d-6980e4e194f9.png)

vcf.lua:
![image](https://user-images.githubusercontent.com/64039885/95085798-ffaf6f00-071f-11eb-8fe9-62bb1b5679a5.png)
![image](https://user-images.githubusercontent.com/64039885/95085878-12c23f00-0720-11eb-8436-227f673c4f0b.png)

vcf Folder:
![image](https://user-images.githubusercontent.com/64039885/95085973-34232b00-0720-11eb-9478-5f797fe798d5.png)

**Comment by JustSteijn25** [comment]
Also I have OneSync infinity. Maybe that is the cause of the problem?

**Comment by Zeemahh** [comment]
Hi, please see issue https://github.com/MrDaGree/ELS-FiveM/issues/90#issuecomment-732083440.
