### ISSUE TITLE
Sirens don't sync with onesync infinity

### ISSUE THREAD

**Issue by IAmRSG** [MrDaGree/ELS-FiveM#86]
### Bug Description
Lights work perfectly fine for everyone, but sirens do not.

### Reproductive Steps
If you are in the area of the player when you activate your sirens, they can hear them. However if you leave their area and return, or if you enter an area with a player that wasnt around when you activated your sirens and lights, they can see the lights, but not hear the sirens.

### Expected Behavior
You're supposed to hear the sirens, but you don't.

### Screenshots
Can't screenshot a sound

### ELS Information
* Version #: 1.92
* Server Version #: FXServer-master SERVER v1.0.0.3142 win32

### Additional Information
There isn't much else to say.

**Comment by Zeemahh** [comment]
Hi, please see issue https://github.com/MrDaGree/ELS-FiveM/issues/90#issuecomment-732083440.
