### ISSUE TITLE
ELS script Error 444 & ELS files cant be read

### ISSUE THREAD

**Issue by JBincer** [MrDaGree/ELS-FiveM#87]
Hello, i got actually two bugs... i searched for solutions for both but i couldn't find anything.
Im using fivepd on my server, there is no esx installed. 

So the first bug is the following one:
https://prnt.sc/vir65j
Im not really familiar with the code stuff, so i have no idea what it means.

Second problem are some ELS vehicles files. Every ELS file for a replaced vehicle (police, police2 e.g.) is working. But for addons its a little bit different - some ELS files are working, some others not. There is the ELS menu in the right corner on every car, so i think ELS is at least detected. I change the steps of lighting (from 0 to 3). Siren is working too. But the lights on the roof aren't working. For some vehicles also the front flashers are working, but not the lights on the roof. I have no idea on what it depends, because some addon cars are working, others dont. In singleplayer every car is working without any problems. I didn't change anything in the .xml files. 
I tried a fix i found on YT to change the .xml file names from normal.xml to BIG.xml, but it didn't change anything. 
Would be great if someone has an idea why some files are working and others don't. 
I fully removed and installed ELS again, but nothing changed - same issues.

### ELS Information
* Version: newest version
* Server Version #: FXServer-master v1.0.0.2967 linux
* Screenshots of config.lua, vcf.lua, vcf folder:
https://prnt.sc/vir6tz
https://prnt.sc/vir6hb
https://prnt.sc/vir742

Hope someone can help me, thanks :)

**Comment by MrDaGree** [comment]
As far as the first error, I cant tell what the issue was without that vehicle VCF file.

For your second issue, if you're on linux the files in the VCF.lua need to match the case of the actual file. If the file is named PoLiCe.XmL then in the VCF.lua it has to match exact

**Comment by JBincer** [comment]
Hey, thanks for answer. For first issue, do you need the ELS file of every vehicle?

Second issue, as you can see the file names of the ELS .xml files and the names in the vcf.lua are the same, but unfortunately they still don't work. So i testet it again to be safe that its not because of the names. I renamed every file to BIG letters, so every vehicles ELS file is called "POLICE.XML" and i added it like "POLICE.xml", in the vcf.lua. Its still not working for some vehicles :/

**Comment by Zeemahh** [comment]
Hi, please see issue https://github.com/MrDaGree/ELS-FiveM/issues/90#issuecomment-732083440.
