### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by CallumHarrisCode** [MrDaGree/ELS-FiveM#88]
Error running system event handling function for resource ELS-FiveM: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/server.lua:744: attempt to call a nil value (global 'debugPrint')
stack traceback:
        server/server.lua:744: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

**Comment by MrDaGree** [comment]
You didnt completely update correctly, youre missing the debugPrint function thats in the utils file. Completely replace everything EXCEPT for VCF files.
