### ISSUE TITLE
Version Number Reporting False

### ISSUE THREAD

**Issue by TayMcKenzieSA** [MrDaGree/ELS-FiveM#89]
the console is reporting that the version is outdated, and to update to version 1.95, however 1.92 seems to be the latest version, at least, available on github.

**Comment by Zeemahh** [comment]
Yea, that's probably a result of the semantic versioning which was not (and unlikely to be) pushed to master. I might just push a change which imitates a 1.95 version.

**Comment by Zeemahh** [comment]
Hi, please see issue https://github.com/MrDaGree/ELS-FiveM/issues/90#issuecomment-732083440.
