### ISSUE TITLE
Stuck with some lights on.

### ISSUE THREAD

**Issue by wes187inc** [MrDaGree/ELS-FiveM#9]
At times you will be come stuck at it looks like stage 2 lighting, lights will still turn on through the stages but when you shut off all lights it still shows some lights on and static not flashing...Found this
![image](https://user-images.githubusercontent.com/29553654/42069197-3af9a480-7b05-11e8-8d66-366c5b8d21fb.png)
right before the lights broke

**Comment by MrDaGree** [comment]
Its known! Thank you though. It should be fixed soon in a development version.

**Comment by MrDaGree** [comment]
Possibly fixed, I do not have a version where the line numbers match anymore to fix. If you run into issues please reopen.
