### ISSUE TITLE
[Reply] Future of the Project 

### ISSUE THREAD

**Issue by Smokiiee** [MrDaGree/ELS-FiveM#90]
hi i need some help with optimiz this resours 
![image](https://user-images.githubusercontent.com/70150561/99372497-8a0ef500-28c0-11eb-9fea-d209a81e1a29.png)

and this with 4 police on with lights on 
![image](https://user-images.githubusercontent.com/70150561/99372472-7ebbc980-28c0-11eb-9c47-e3655b6d06b3.png)

**Comment by Zeemahh** [comment]
Any PR will be accepted regarding performance, however, no support or changes will be pushed from the maintainers<sup>1</sup>.

<sup>1</sup> Inevitably, the development for ELS-FiveM has reached the end. Nothing much can be implemented apart from improving performance. I, personally, don't have time to maintain this project further. But, if anybody feels like they want to make changes and PRs for performance improvements, I'd be more than happy to accept them. This is a small announcement for the future of this project, so I guess you should all read this.
