### ISSUE TITLE
Lights flicker strangely

### ISSUE THREAD

**Issue by FunnyBuddys** [MrDaGree/ELS-FiveM#93]
### Bug Description

All the lights flicker in a very strange and unnatural way.

I tried to put it in a GIF file, but you can't see it that well on it.

### Screenshots

![2020-12-18 13-07-05](https://user-images.githubusercontent.com/16995710/102613281-81fddb80-4132-11eb-81f1-3c26866d8b7a.gif)

### ELS Information
* Version #: 1.92
* Server Version #: v1.0.0.3184 linux 
* Screenshots of config.lua, vcf.lua, vcf folder: 
![Screenshot_6](https://user-images.githubusercontent.com/16995710/102613421-bb364b80-4132-11eb-8d2a-5943593dfa30.png)
![Screenshot_7](https://user-images.githubusercontent.com/16995710/102613522-ed47ad80-4132-11eb-831f-400d2e0d4713.png)
![Screenshot_8](https://user-images.githubusercontent.com/16995710/102613529-efaa0780-4132-11eb-8721-abe92ff69e00.png)

**Comment by Proxximaa** [comment]
try to play around with light and flash delay

**Comment by FunnyBuddys** [comment]
> try to play around with light and flash delay

Doesn't work.

**Comment by LeonTReal** [comment]
I'm having the same problem with my FiveM Server

**Comment by MrDaGree** [comment]
Honestly without a video i cannot do anything as in the GIF it looks perfectly fine. Feel free to make a new issue with a video
