### ISSUE TITLE
I 

### ISSUE THREAD

**Issue by sflabrie** [MrDaGree/ELS-FiveM#94]
I have this error when i install the version 1.92 without any modification:

SCRIPT ERROR: @ELS-FiveM/server/server.lua:750: No VCF list found, please have a file called vcf.lua - see vcf.default.lua for example.
handler (@ELS-FiveM/server/server.lua:750)

### ELS Information
* Version # 1.92 
* Server Version: "FXServer-master v1.0.0.3184 linux"

thanks

**Comment by MrDaGree** [comment]
It quite literally tells you what to do

**Comment by sflabrie** [comment]
I change NOTHING in your files. 
And in your VCF you already put a few car  
------------
vcf_files = {
	"POLICE.xml",
	"POLICE2.xml",
	"POLICE3.xml",
	"POLICE4.xml",
	"PRANGER.xml",
	"SHERIFF2.xml",
	"AMBULANCE.xml",
	"FBI2.xml",
	"FBI.xml",
	"SADLER.xml",
	"FIRETRUK.xml",
	"hwaycar2.xml",
	"hwaycar3.xml",
	"hwaycar4.xml",
	"hwaycar5.xml",
	"hwaycar6.xml",
	"hwaycar7.xml",
	"hwaycar8.xml",
	"hwaycar9.xml",
	"hwaycar10.xml",
	"tflatbed4.xml",
	"policeold1.xml",
	"policeold2.xml"
}
-----------

But i have the error....

**Comment by At0micA55** [comment]
I have found the problem. I am working with sflabrie and in your default files your vcf.lua that the fxmanifest is looking for is called vcf.default.lua so the fxmanifest tell to load a file that technically doesn't exist... I would suggest changing your vcf.default.lua to vcf.lua to prevent issues like that in the futur. People need to be able to test your creations without needing to change any files at first and then change if needed ^^ 

This is just my suggestion ^^

**Comment by MrDaGree** [comment]
This is not an issue... if you guys read the README on the main page you would know that this is intenional.

https://mrdagree.com/u/3hPfM.png
