### ISSUE TITLE
light already on when the vehicle spawns

### ISSUE THREAD

**Issue by SebastienSueur** [MrDaGree/ELS-FiveM#97]
### Bug Description
When I spawn a car from the "/car" chat or from the garage area of ​​esx_policejob there are lights that are already on it is random sometimes there are and sometimes not and it is not always the same that are lit. I don't know if it's a bug or if it's normal.But on the other hand sometimes when I spawn a vehicle it may be that no light is on and that's what I want

### Reproductive Steps
hen I spawn a car (I tried with several packs and it does the same thing)

### Screenshots
https://goopics.net/i/Q8NEl
https://goopics.net/i/l2K9E
https://goopics.net/i/En47j

### ELS Information
* Version :  1.92
* Server Version : 3404
* Screenshots :
https://goopics.net/i/LNa7d
https://goopics.net/i/5Ox7g
https://goopics.net/i/rZENj

**Comment by Dkamps18** [comment]
Normal GTA behavior all lights are extra's on the vehicle and GTA spawns cars with random extra's enabled, can be easily fixed by just activating the lights for a second.

**Comment by tobiaslindwall** [comment]
The problem becomes when you request backup, ambulance or fire truck. No vehicles using "ELS-FiveM" arrive at the scene with working lights, as the vehicles have spawned with some light on. You do not get that problem with ELS in LSPDFR. As long as you play RP with other players its not a problem becuase (just like you said) just have to activate it for a second. The problem occurs when playing with AI. Would be really nice if it could be fixed.

**Comment by MrDaGree** [comment]
It's not an issue with ELS... it was never implemented in ELS FiveM and as far as AI having working lights, also not implemented.
