### ISSUE TITLE
Unexpected symbol with data_version

### ISSUE THREAD

**Issue by jtrudeau1530** [MrDaGree/ELS-FiveM#99]
<<ELS-FiveM/server/server.lua>>

Unexpected symbol '?' fixed by removing on line 8, 32, and 83

Looks like an updater check however, I had to remove it for the script to work.

**Comment by ZimeZy** [comment]
Hey how did you fix this, I got the same error with Line 8 @ELS-FiveM/server/server.lua:8: 'then' expected near '?'

**Comment by lze3** [comment]
Not a bug. Update your server binaries.

**Comment by jtrudeau1530** [comment]
> Hey how did you fix this, I got the same error with Line 8 @ELS-FiveM/server/server.lua:8: 'then' expected near '?'

I said how I fixed it in my comment, however just updating your server binaries will work as well

**Comment by lze3** [comment]
> > Hey how did you fix this, I got the same error with Line 8 @ELS-FiveM/server/server.lua:8: 'then' expected near '?'
> 
> 
> 
> I said how I fixed it in my comment

That's not a fix.
